version: '2'

services:

  elastic:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
       - elastic:/usr/share/elasticsearch/data

  kibana:
    image: kibana-nested
    build: kibana-nested
    ports:
      - "5601:5601"
    command: ./bin/kibana -e http://elastic:9200 -H 0.0.0.0 -p 5601

  indexer:
    image: gs_indexer
    build: indexer
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - /tmp/urls:/data
      # just for devel:
      - ./indexer:/usr/src/app
    command: ./indexer.py /data --elastic http://elastic:9200 --log=DEBUG

volumes:
  elastic:
