version: '2'

services:

  elastic:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
       - elastic:/usr/share/elasticsearch/data

  kibana:
    image: kibana-nested
    build: kibana-nested
    ports:
      - "5601:5601"
    command: ./bin/kibana -e http://elastic:9200 -H 0.0.0.0 -p 5601

  indexer:
    image: gs_indexer
    build: indexer
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - /tmp/urls:/data
      # just for devel:
      - ./indexer:/usr/src/app
    command: ./indexer.py /data --elastic http://elastic:9200

volumes:
  elastic:
